version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_API_KEY=${DATA_API_KEY}
    command: ["python3", "api.py"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - 5173:5173
    command: ["serve", "-s", "build", "-l", "5173"]
